//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 08:22:12 AM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CONFType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CONFType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OSCFG" type="{}OSCFGType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CONFType", propOrder = {
    "name",
    "oscfg"
})
public class CONFType {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "OSCFG", required = true)
    protected OSCFGType oscfg;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the oscfg property.
     * 
     * @return
     *     possible object is
     *     {@link OSCFGType }
     *     
     */
    public OSCFGType getOSCFG() {
        return oscfg;
    }

    /**
     * Sets the value of the oscfg property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSCFGType }
     *     
     */
    public void setOSCFG(OSCFGType value) {
        this.oscfg = value;
    }

}
