//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 08:22:12 AM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bosch.tisched.rteconfig.generator.osconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CONF_QNAME = new QName("", "CONF");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bosch.tisched.rteconfig.generator.osconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CONFType }
     * 
     */
    public CONFType createCONFType() {
        return new CONFType();
    }

    /**
     * Create an instance of {@link OSPROCESSType }
     * 
     */
    public OSPROCESSType createOSPROCESSType() {
        return new OSPROCESSType();
    }

    /**
     * Create an instance of {@link OSAPPLICATIONIDMAPPINGSType }
     * 
     */
    public OSAPPLICATIONIDMAPPINGSType createOSAPPLICATIONIDMAPPINGSType() {
        return new OSAPPLICATIONIDMAPPINGSType();
    }

    /**
     * Create an instance of {@link OSBSWMODULEINSTANCEType }
     * 
     */
    public OSBSWMODULEINSTANCEType createOSBSWMODULEINSTANCEType() {
        return new OSBSWMODULEINSTANCEType();
    }

    /**
     * Create an instance of {@link OSEVENTType }
     * 
     */
    public OSEVENTType createOSEVENTType() {
        return new OSEVENTType();
    }

    /**
     * Create an instance of {@link OSAPPLICATIONIDMAPPINGType }
     * 
     */
    public OSAPPLICATIONIDMAPPINGType createOSAPPLICATIONIDMAPPINGType() {
        return new OSAPPLICATIONIDMAPPINGType();
    }

    /**
     * Create an instance of {@link OSTASKType }
     * 
     */
    public OSTASKType createOSTASKType() {
        return new OSTASKType();
    }

    /**
     * Create an instance of {@link OSGENERALCFGType }
     * 
     */
    public OSGENERALCFGType createOSGENERALCFGType() {
        return new OSGENERALCFGType();
    }

    /**
     * Create an instance of {@link OSTASKCONTEXTType }
     * 
     */
    public OSTASKCONTEXTType createOSTASKCONTEXTType() {
        return new OSTASKCONTEXTType();
    }

    /**
     * Create an instance of {@link OSCOMPONENTINSTANCEType }
     * 
     */
    public OSCOMPONENTINSTANCEType createOSCOMPONENTINSTANCEType() {
        return new OSCOMPONENTINSTANCEType();
    }

    /**
     * Create an instance of {@link OSCFGType }
     * 
     */
    public OSCFGType createOSCFGType() {
        return new OSCFGType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CONFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONF")
    public JAXBElement<CONFType> createCONF(CONFType value) {
        return new JAXBElement<CONFType>(_CONF_QNAME, CONFType.class, null, value);
    }

}
