//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 08:22:12 AM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OS_BSWMODULEINSTANCEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OS_BSWMODULEINSTANCEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OS_BSWMODULEINSTANCENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OS_BSWIMPLEMENTATIONREF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_APPLICATIONID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OS_BSWMODULEINSTANCEType", propOrder = {
    "osbswmoduleinstancename",
    "osbswimplementationref",
    "osapplicationid"
})
public class OSBSWMODULEINSTANCEType {

    @XmlElement(name = "OS_BSWMODULEINSTANCENAME", required = true)
    protected String osbswmoduleinstancename;
    @XmlElement(name = "OS_BSWIMPLEMENTATIONREF")
    protected String osbswimplementationref;
    @XmlElement(name = "OS_APPLICATIONID")
    protected List<String> osapplicationid;

    /**
     * Gets the value of the osbswmoduleinstancename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSBSWMODULEINSTANCENAME() {
        return osbswmoduleinstancename;
    }

    /**
     * Sets the value of the osbswmoduleinstancename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSBSWMODULEINSTANCENAME(String value) {
        this.osbswmoduleinstancename = value;
    }

    /**
     * Gets the value of the osbswimplementationref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSBSWIMPLEMENTATIONREF() {
        return osbswimplementationref;
    }

    /**
     * Sets the value of the osbswimplementationref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSBSWIMPLEMENTATIONREF(String value) {
        this.osbswimplementationref = value;
    }

    /**
     * Gets the value of the osapplicationid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the osapplicationid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOSAPPLICATIONID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOSAPPLICATIONID() {
        if (osapplicationid == null) {
            osapplicationid = new ArrayList<String>();
        }
        return this.osapplicationid;
    }

}
