//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 08:22:12 AM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OSCFGType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OSCFGType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;sequence>
 *           &lt;element name="OS_GENERALCFG" type="{}OS_GENERALCFGType"/>
 *           &lt;element name="OS_APPLICATIONIDMAPPINGS" type="{}OS_APPLICATIONIDMAPPINGSType"/>
 *           &lt;element name="OS_TASK" type="{}OS_TASKType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="OS_COMPONENTINSTANCE" type="{}OS_COMPONENTINSTANCEType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="OS_BSWMODULEINSTANCE" type="{}OS_BSWMODULEINSTANCEType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="OS_TASKCONTEXT" type="{}OS_TASKCONTEXTType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OSCFGType", propOrder = {
    "osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK"
})
public class OSCFGType {

    @XmlElements({
        @XmlElement(name = "OS_GENERALCFG", type = OSGENERALCFGType.class),
        @XmlElement(name = "OS_APPLICATIONIDMAPPINGS", type = OSAPPLICATIONIDMAPPINGSType.class),
        @XmlElement(name = "OS_TASK", type = OSTASKType.class),
        @XmlElement(name = "OS_COMPONENTINSTANCE", type = OSCOMPONENTINSTANCEType.class),
        @XmlElement(name = "OS_BSWMODULEINSTANCE", type = OSBSWMODULEINSTANCEType.class),
        @XmlElement(name = "OS_TASKCONTEXT", type = OSTASKCONTEXTType.class)
    })
    protected List<Object> osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK;

    /**
     * Gets the value of the osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOSGENERALCFGAndOSAPPLICATIONIDMAPPINGSAndOSTASK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OSGENERALCFGType }
     * {@link OSAPPLICATIONIDMAPPINGSType }
     * {@link OSTASKType }
     * {@link OSCOMPONENTINSTANCEType }
     * {@link OSBSWMODULEINSTANCEType }
     * {@link OSTASKCONTEXTType }
     * 
     * 
     */
    public List<Object> getOSGENERALCFGAndOSAPPLICATIONIDMAPPINGSAndOSTASK() {
        if (osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK == null) {
            osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK = new ArrayList<Object>();
        }
        return this.osgeneralcfgAndOSAPPLICATIONIDMAPPINGSAndOSTASK;
    }

}
