//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.03.08 at 06:25:05 PM IST
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for OS_COMPONENTINSTANCEType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OS_COMPONENTINSTANCEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OS_INSTANCENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OS_COMPONENTTYPEREF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_APPLICATIONID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OS_NOMEMMAPGEN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OS_COMPONENTINSTANCEType", propOrder = {
    "osinstancename",
    "oscomponenttyperef",
    "osapplicationid",
    "osnomemmapgen" })
public class OSCOMPONENTINSTANCEType {

  @XmlElement(name = "OS_INSTANCENAME", required = true)
  protected String osinstancename;
  @XmlElement(name = "OS_COMPONENTTYPEREF")
  protected String oscomponenttyperef;
  @XmlElement(name = "OS_APPLICATIONID")
  protected List<String> osapplicationid;
  @XmlElement(name = "OS_NOMEMMAPGEN")
  protected Boolean osnomemmapgen = false;

  /**
   * Gets the value of the osinstancename property.
   * 
   * @return possible object is {@link String }
   */
  public String getOSINSTANCENAME() {
    return this.osinstancename;
  }

  /**
   * Sets the value of the osinstancename property.
   * 
   * @param value allowed object is {@link String }
   */
  public void setOSINSTANCENAME(final String value) {
    this.osinstancename = value;
  }

  /**
   * Gets the value of the oscomponenttyperef property.
   * 
   * @return possible object is {@link String }
   */
  public String getOSCOMPONENTTYPEREF() {
    return this.oscomponenttyperef;
  }

  /**
   * Sets the value of the oscomponenttyperef property.
   * 
   * @param value allowed object is {@link String }
   */
  public void setOSCOMPONENTTYPEREF(final String value) {
    this.oscomponenttyperef = value;
  }

  /**
   * Gets the value of the osapplicationid property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the osapplicationid property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getOSAPPLICATIONID().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getOSAPPLICATIONID() {
    if (this.osapplicationid == null) {
      this.osapplicationid = new ArrayList<String>();
    }
    return this.osapplicationid;
  }

  /**
   * Gets the value of the osnomemmapgen property.
   * 
   * @return possible object is {@link Boolean }
   */
  public Boolean isOSNOMEMMAPGEN() {
    return this.osnomemmapgen;
  }

  /**
   * Sets the value of the osnomemmapgen property.
   * 
   * @param value allowed object is {@link Boolean }
   */
  public void setOSNOMEMMAPGEN(final Boolean value) {
    this.osnomemmapgen = value;
  }

}
