//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 08:22:12 AM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OS_TASKTYPEType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OS_TASKTYPEType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SOFTWARE"/>
 *     &lt;enumeration value="INIT"/>
 *     &lt;enumeration value="ISR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OS_TASKTYPEType")
@XmlEnum
public enum OSTASKTYPEType {

    SOFTWARE,
    INIT,
    ISR;

    public String value() {
        return name();
    }

    public static OSTASKTYPEType fromValue(String v) {
        return valueOf(v);
    }

}
