//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.18 at 02:36:43 PM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OS_TASKType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OS_TASKType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="OS_EVENT" type="{}OS_EVENTType"/>
 *           &lt;element name="OS_PROCESS" type="{}OS_PROCESSType"/>
 *         &lt;/choice>
 *         &lt;element name="OS_PPORTPROTOTYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_BSWRELEASEDTRIGGER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_CHAINTASK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_COOPTASK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_RTETASKHOOKS" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OS_TASKCYCLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_TASKEVENTTYPE" type="{}OS_TASKEVENTTYPEType" minOccurs="0"/>
 *         &lt;element name="OS_TSKMR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OS_APPLICATIONID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OS_TASKNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OS_TASKPRIORITY" type="{}OS_PRIOBaseType"/>
 *         &lt;element name="OS_TASKTYPE" type="{}OS_TASKTYPEType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OS_TASKType", propOrder = {
    "oseventOrOSPROCESS",
    "ospportprototype",
    "osbswreleasedtrigger",
    "oschaintask",
    "oscooptask",
    "osrtetaskhooks",
    "ostaskcycle",
    "ostaskeventtype",
    "ostskmr",
    "osapplicationid",
    "ostaskname",
    "ostaskpriority",
    "ostasktype"
})
public class OSTASKType {

    @XmlElements({
        @XmlElement(name = "OS_EVENT", type = OSEVENTType.class),
        @XmlElement(name = "OS_PROCESS", type = OSPROCESSType.class)
    })
    protected List<Object> oseventOrOSPROCESS;
    @XmlElement(name = "OS_PPORTPROTOTYPE")
    protected String ospportprototype;
    @XmlElement(name = "OS_BSWRELEASEDTRIGGER")
    protected String osbswreleasedtrigger;
    @XmlElement(name = "OS_CHAINTASK")
    protected String oschaintask;
    @XmlElement(name = "OS_COOPTASK")
    protected String oscooptask;
    @XmlElement(name = "OS_RTETASKHOOKS")
    protected Boolean osrtetaskhooks;
    @XmlElement(name = "OS_TASKCYCLE")
    protected String ostaskcycle;
    @XmlElement(name = "OS_TASKEVENTTYPE")
    @XmlSchemaType(name = "string")
    protected OSTASKEVENTTYPEType ostaskeventtype;
    @XmlElement(name = "OS_TSKMR")
    protected String ostskmr;
    @XmlElement(name = "OS_APPLICATIONID", required = true)
    protected String osapplicationid;
    @XmlElement(name = "OS_TASKNAME", required = true)
    protected String ostaskname;
    @XmlElement(name = "OS_TASKPRIORITY", required = true)
    protected BigInteger ostaskpriority;
    @XmlElement(name = "OS_TASKTYPE", required = true)
    @XmlSchemaType(name = "string")
    protected OSTASKTYPEType ostasktype;

    /**
     * Gets the value of the oseventOrOSPROCESS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oseventOrOSPROCESS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOSEVENTOrOSPROCESS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OSEVENTType }
     * {@link OSPROCESSType }
     * 
     * 
     */
    public List<Object> getOSEVENTOrOSPROCESS() {
        if (oseventOrOSPROCESS == null) {
            oseventOrOSPROCESS = new ArrayList<Object>();
        }
        return this.oseventOrOSPROCESS;
    }

    /**
     * Gets the value of the ospportprototype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSPPORTPROTOTYPE() {
        return ospportprototype;
    }

    /**
     * Sets the value of the ospportprototype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSPPORTPROTOTYPE(String value) {
        this.ospportprototype = value;
    }

    /**
     * Gets the value of the osbswreleasedtrigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSBSWRELEASEDTRIGGER() {
        return osbswreleasedtrigger;
    }

    /**
     * Sets the value of the osbswreleasedtrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSBSWRELEASEDTRIGGER(String value) {
        this.osbswreleasedtrigger = value;
    }

    /**
     * Gets the value of the oschaintask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSCHAINTASK() {
        return oschaintask;
    }

    /**
     * Sets the value of the oschaintask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSCHAINTASK(String value) {
        this.oschaintask = value;
    }

    /**
     * Gets the value of the oscooptask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSCOOPTASK() {
        return oscooptask;
    }

    /**
     * Sets the value of the oscooptask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSCOOPTASK(String value) {
        this.oscooptask = value;
    }

    /**
     * Gets the value of the osrtetaskhooks property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOSRTETASKHOOKS() {
        return osrtetaskhooks;
    }

    /**
     * Sets the value of the osrtetaskhooks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOSRTETASKHOOKS(Boolean value) {
        this.osrtetaskhooks = value;
    }

    /**
     * Gets the value of the ostaskcycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSTASKCYCLE() {
        return ostaskcycle;
    }

    /**
     * Sets the value of the ostaskcycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSTASKCYCLE(String value) {
        this.ostaskcycle = value;
    }

    /**
     * Gets the value of the ostaskeventtype property.
     * 
     * @return
     *     possible object is
     *     {@link OSTASKEVENTTYPEType }
     *     
     */
    public OSTASKEVENTTYPEType getOSTASKEVENTTYPE() {
        return ostaskeventtype;
    }

    /**
     * Sets the value of the ostaskeventtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSTASKEVENTTYPEType }
     *     
     */
    public void setOSTASKEVENTTYPE(OSTASKEVENTTYPEType value) {
        this.ostaskeventtype = value;
    }

    /**
     * Gets the value of the ostskmr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSTSKMR() {
        return ostskmr;
    }

    /**
     * Sets the value of the ostskmr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSTSKMR(String value) {
        this.ostskmr = value;
    }

    /**
     * Gets the value of the osapplicationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSAPPLICATIONID() {
        return osapplicationid;
    }

    /**
     * Sets the value of the osapplicationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSAPPLICATIONID(String value) {
        this.osapplicationid = value;
    }

    /**
     * Gets the value of the ostaskname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSTASKNAME() {
        return ostaskname;
    }

    /**
     * Sets the value of the ostaskname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSTASKNAME(String value) {
        this.ostaskname = value;
    }

    /**
     * Gets the value of the ostaskpriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOSTASKPRIORITY() {
        return ostaskpriority;
    }

    /**
     * Sets the value of the ostaskpriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOSTASKPRIORITY(BigInteger value) {
        this.ostaskpriority = value;
    }

    /**
     * Gets the value of the ostasktype property.
     * 
     * @return
     *     possible object is
     *     {@link OSTASKTYPEType }
     *     
     */
    public OSTASKTYPEType getOSTASKTYPE() {
        return ostasktype;
    }

    /**
     * Sets the value of the ostasktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSTASKTYPEType }
     *     
     */
    public void setOSTASKTYPE(OSTASKTYPEType value) {
        this.ostasktype = value;
    }

}
