//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.08 at 06:25:05 PM IST 
//


package com.bosch.tisched.rteconfig.generator.osconfig;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OS_TASKEVENTTYPEType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OS_TASKEVENTTYPEType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="ITO"/>
 *     &lt;enumeration value="ETO"/>
 *     &lt;enumeration value="BG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OS_TASKEVENTTYPEType")
@XmlEnum
public enum OSTASKEVENTTYPEType {

    I,
    T,
    ITO,
    ETO,
    BG;

    public String value() {
        return name();
    }

    public static OSTASKEVENTTYPEType fromValue(String v) {
        return valueOf(v);
    }

}
