//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.18 at 02:48:15 PM IST 
//


package com.bosch.tisched.rteconfig.generator.rtememmap.xpt;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bosch.tisched.rteconfig.generator.memmapxpt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bosch.tisched.rteconfig.generator.memmapxpt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TARGETS }
     * 
     */
    public TARGETS createTARGETS() {
        return new TARGETS();
    }

    /**
     * Create an instance of {@link TARGETS.TARGET }
     * 
     */
    public TARGETS.TARGET createTARGETSTARGET() {
        return new TARGETS.TARGET();
    }

    /**
     * Create an instance of {@link TARGETS.TARGET.SECTIONS }
     * 
     */
    public TARGETS.TARGET.SECTIONS createTARGETSTARGETSECTIONS() {
        return new TARGETS.TARGET.SECTIONS();
    }

    /**
     * Create an instance of {@link TARGETS.TARGET.GENERALKEYWORDS }
     * 
     */
    public TARGETS.TARGET.GENERALKEYWORDS createTARGETSTARGETGENERALKEYWORDS() {
        return new TARGETS.TARGET.GENERALKEYWORDS();
    }

    /**
     * Create an instance of {@link TARGETS.TARGET.SECTIONS.SECTION }
     * 
     */
    public TARGETS.TARGET.SECTIONS.SECTION createTARGETSTARGETSECTIONSSECTION() {
        return new TARGETS.TARGET.SECTIONS.SECTION();
    }

}
