//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.07.27 at 07:54:54 PM IST
//


package com.bosch.tisched.rteconfig.generator.rtememmap.xpt;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TARGET" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="XPT-SECTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GENERAL_KEYWORDS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PRAGMA_SECTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SW_COMPONENT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="OS_APPLICATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BSW_MODULE_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="OS_TASK_NAME_PATTERN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ALIGNMENT_OPERATOR_8BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ALIGNMENT_OPERATOR_BOOLEAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ALIGNMENT_OPERATOR_16BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ALIGNMENT_OPERATOR_32BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ALIGNMENT_OPERATOR_64BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SECTIONS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SECTION" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OPTIONAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="OPTIONAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FINAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="LINKER_FLAG_KEYWORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="FINAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="DEFAULT_INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="DEFAULT_INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "target" })
@XmlRootElement(name = "TARGETS")
public class TARGETS {

  @XmlElement(name = "TARGET")
  protected List<TARGETS.TARGET> target;

  /**
   * Gets the value of the target property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
   * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
   * the target property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getTARGET().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link TARGETS.TARGET }
   */
  public List<TARGETS.TARGET> getTARGET() {
    if (this.target == null) {
      this.target = new ArrayList<TARGETS.TARGET>();
    }
    return this.target;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="XPT-SECTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="GENERAL_KEYWORDS">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="PRAGMA_SECTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="SW_COMPONENT" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="OS_APPLICATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="BSW_MODULE_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="OS_TASK_NAME_PATTERN" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="ALIGNMENT_OPERATOR_8BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="ALIGNMENT_OPERATOR_BOOLEAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="ALIGNMENT_OPERATOR_16BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="ALIGNMENT_OPERATOR_32BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="ALIGNMENT_OPERATOR_64BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="SECTIONS">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="SECTION" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="OPTIONAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="OPTIONAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="FINAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="LINKER_FLAG_KEYWORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="FINAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="DEFAULT_INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                             &lt;element name="DEFAULT_INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "shortname", "xptsection", "generalkeywords", "sections" })
  public static class TARGET {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "XPT-SECTION", required = true)
    protected String xptsection;
    @XmlElement(name = "GENERAL_KEYWORDS", required = true)
    protected TARGETS.TARGET.GENERALKEYWORDS generalkeywords;
    @XmlElement(name = "SECTIONS", required = true)
    protected TARGETS.TARGET.SECTIONS sections;

    /**
     * Gets the value of the shortname property.
     * 
     * @return possible object is {@link String }
     */
    public String getSHORTNAME() {
      return this.shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSHORTNAME(final String value) {
      this.shortname = value;
    }

    /**
     * Gets the value of the xptsection property.
     * 
     * @return possible object is {@link String }
     */
    public String getXPTSECTION() {
      return this.xptsection;
    }

    /**
     * Sets the value of the xptsection property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setXPTSECTION(final String value) {
      this.xptsection = value;
    }

    /**
     * Gets the value of the generalkeywords property.
     * 
     * @return possible object is {@link TARGETS.TARGET.GENERALKEYWORDS }
     */
    public TARGETS.TARGET.GENERALKEYWORDS getGENERALKEYWORDS() {
      return this.generalkeywords;
    }

    /**
     * Sets the value of the generalkeywords property.
     * 
     * @param value allowed object is {@link TARGETS.TARGET.GENERALKEYWORDS }
     */
    public void setGENERALKEYWORDS(final TARGETS.TARGET.GENERALKEYWORDS value) {
      this.generalkeywords = value;
    }

    /**
     * Gets the value of the sections property.
     * 
     * @return possible object is {@link TARGETS.TARGET.SECTIONS }
     */
    public TARGETS.TARGET.SECTIONS getSECTIONS() {
      return this.sections;
    }

    /**
     * Sets the value of the sections property.
     * 
     * @param value allowed object is {@link TARGETS.TARGET.SECTIONS }
     */
    public void setSECTIONS(final TARGETS.TARGET.SECTIONS value) {
      this.sections = value;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PRAGMA_SECTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SW_COMPONENT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OS_APPLICATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BSW_MODULE_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OS_TASK_NAME_PATTERN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ALIGNMENT_OPERATOR_8BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ALIGNMENT_OPERATOR_BOOLEAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ALIGNMENT_OPERATOR_16BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ALIGNMENT_OPERATOR_32BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ALIGNMENT_OPERATOR_64BIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pragmasection",
        "swcomponent",
        "osapplication",
        "bswmoduledescription",
        "ostasknamepattern",
        "alignmentoperator8BIT",
        "alignmentoperatorboolean",
        "alignmentoperator16BIT",
        "alignmentoperator32BIT",
        "alignmentoperator64BIT" })
    public static class GENERALKEYWORDS {

      @XmlElement(name = "PRAGMA_SECTION", required = true)
      protected String pragmasection;
      @XmlElement(name = "SW_COMPONENT", required = true)
      protected String swcomponent;
      @XmlElement(name = "OS_APPLICATION", required = true)
      protected String osapplication;
      @XmlElement(name = "BSW_MODULE_DESCRIPTION", required = true)
      protected String bswmoduledescription;
      @XmlElement(name = "OS_TASK_NAME_PATTERN", required = true)
      protected String ostasknamepattern;
      @XmlElement(name = "ALIGNMENT_OPERATOR_8BIT")
      protected String alignmentoperator8BIT;
      @XmlElement(name = "ALIGNMENT_OPERATOR_BOOLEAN")
      protected String alignmentoperatorboolean;
      @XmlElement(name = "ALIGNMENT_OPERATOR_16BIT")
      protected String alignmentoperator16BIT;
      @XmlElement(name = "ALIGNMENT_OPERATOR_32BIT")
      protected String alignmentoperator32BIT;
      @XmlElement(name = "ALIGNMENT_OPERATOR_64BIT")
      protected String alignmentoperator64BIT;

      public String getValue(final GENERAL_KEYWORD generalKeyword) {

        String value = "";
        switch (generalKeyword) {

          case PRAGMA_SECTION:
            return getPRAGMASECTION();
          case SW_COMPONENT:
            return getSWCOMPONENT();
          case OS_APPLICATION:
            return getOSAPPLICATION();
          case BSW_MODULE_DESCRIPTION:
            return getBSWMODULEDESCRIPTION();
          case OS_TASK_NAME_PATTERN:
            return getOSTASKNAMEPATTERN();
          case ALIGNMENT_OPERATOR_8BIT:
            return getALIGNMENTOPERATOR8BIT();
          case ALIGNMENT_OPERATOR_BOOLEAN:
            return getALIGNMENTOPERATORBOOLEAN();
          case ALIGNMENT_OPERATOR_16BIT:
            return getALIGNMENTOPERATOR16BIT();
          case ALIGNMENT_OPERATOR_32BIT:
            return getALIGNMENTOPERATOR32BIT();
          case ALIGNMENT_OPERATOR_64BIT:
            return getALIGNMENTOPERATOR64BIT();
          default:
            return value;
        }
      }

      /**
       * Gets the value of the pragmasection property.
       *
       * @return possible object is {@link String }
       */
      public String getPRAGMASECTION() {
        return this.pragmasection;
      }

      /**
       * Sets the value of the pragmasection property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setPRAGMASECTION(final String value) {
        this.pragmasection = value;
      }

      /**
       * Gets the value of the swcomponent property.
       * 
       * @return possible object is {@link String }
       */
      public String getSWCOMPONENT() {
        return this.swcomponent;
      }

      /**
       * Sets the value of the swcomponent property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setSWCOMPONENT(final String value) {
        this.swcomponent = value;
      }

      /**
       * Gets the value of the osapplication property.
       * 
       * @return possible object is {@link String }
       */
      public String getOSAPPLICATION() {
        return this.osapplication;
      }

      /**
       * Sets the value of the osapplication property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setOSAPPLICATION(final String value) {
        this.osapplication = value;
      }

      /**
       * Gets the value of the bswmoduledescription property.
       * 
       * @return possible object is {@link String }
       */
      public String getBSWMODULEDESCRIPTION() {
        return this.bswmoduledescription;
      }

      /**
       * Sets the value of the bswmoduledescription property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setBSWMODULEDESCRIPTION(final String value) {
        this.bswmoduledescription = value;
      }

      /**
       * Gets the value of the ostasknamepattern property.
       * 
       * @return possible object is {@link String }
       */
      public String getOSTASKNAMEPATTERN() {
        return this.ostasknamepattern;
      }

      /**
       * Sets the value of the ostasknamepattern property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setOSTASKNAMEPATTERN(final String value) {
        this.ostasknamepattern = value;
      }

      /**
       * Gets the value of the alignmentoperator8BIT property.
       * 
       * @return possible object is {@link String }
       */
      public String getALIGNMENTOPERATOR8BIT() {
        return this.alignmentoperator8BIT;
      }

      /**
       * Sets the value of the alignmentoperator8BIT property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setALIGNMENTOPERATOR8BIT(final String value) {
        this.alignmentoperator8BIT = value;
      }

      /**
       * Gets the value of the alignmentoperatorboolean property.
       * 
       * @return possible object is {@link String }
       */
      public String getALIGNMENTOPERATORBOOLEAN() {
        return this.alignmentoperatorboolean;
      }

      /**
       * Sets the value of the alignmentoperatorboolean property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setALIGNMENTOPERATORBOOLEAN(final String value) {
        this.alignmentoperatorboolean = value;
      }

      /**
       * Gets the value of the alignmentoperator16BIT property.
       * 
       * @return possible object is {@link String }
       */
      public String getALIGNMENTOPERATOR16BIT() {
        return this.alignmentoperator16BIT;
      }

      /**
       * Sets the value of the alignmentoperator16BIT property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setALIGNMENTOPERATOR16BIT(final String value) {
        this.alignmentoperator16BIT = value;
      }

      /**
       * Gets the value of the alignmentoperator32BIT property.
       * 
       * @return possible object is {@link String }
       */
      public String getALIGNMENTOPERATOR32BIT() {
        return this.alignmentoperator32BIT;
      }

      /**
       * Sets the value of the alignmentoperator32BIT property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setALIGNMENTOPERATOR32BIT(final String value) {
        this.alignmentoperator32BIT = value;
      }

      /**
       * Gets the value of the alignmentoperator64BIT property.
       * 
       * @return possible object is {@link String }
       */
      public String getALIGNMENTOPERATOR64BIT() {
        return this.alignmentoperator64BIT;
      }

      /**
       * Sets the value of the alignmentoperator64BIT property.
       * 
       * @param value allowed object is {@link String }
       */
      public void setALIGNMENTOPERATOR64BIT(final String value) {
        this.alignmentoperator64BIT = value;
      }

    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SECTION" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="OPTIONAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="OPTIONAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FINAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="LINKER_FLAG_KEYWORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="FINAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DEFAULT_INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DEFAULT_INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "section" })
    public static class SECTIONS {

      @XmlElement(name = "SECTION")
      protected List<TARGETS.TARGET.SECTIONS.SECTION> section;

      /**
       * Gets the value of the section property.
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
       * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
       * for the section property.
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getSECTION().add(newItem);
       * </pre>
       * <p>
       * Objects of the following type(s) are allowed in the list {@link TARGETS.TARGET.SECTIONS.SECTION }
       */
      public List<TARGETS.TARGET.SECTIONS.SECTION> getSECTION() {
        if (this.section == null) {
          this.section = new ArrayList<TARGETS.TARGET.SECTIONS.SECTION>();
        }
        return this.section;
      }


      /**
       * <p>
       * Java class for anonymous complex type.
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="OPTIONAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="OPTIONAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="FINAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="LINKER_FLAG_KEYWORD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="FINAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="DEFAULT_INITIAL_KEYWORD_1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *         &lt;element name="DEFAULT_INITIAL_KEYWORD_2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = {
          "shortname",
          "optionalkeyword1",
          "optionalkeyword2",
          "initialkeyword1",
          "finalkeyword1",
          "initialkeyword2",
          "linkerflagkeyword",
          "finalkeyword2",
          "defaultinitialkeyword1",
          "defaultinitialkeyword2" })
      public static class SECTION {

        @XmlElement(name = "SHORT-NAME", required = true)
        protected String shortname;
        @XmlElement(name = "OPTIONAL_KEYWORD_1")
        protected String optionalkeyword1;
        @XmlElement(name = "OPTIONAL_KEYWORD_2")
        protected String optionalkeyword2;
        @XmlElement(name = "INITIAL_KEYWORD_1", required = true)
        protected String initialkeyword1;
        @XmlElement(name = "FINAL_KEYWORD_1")
        protected String finalkeyword1;
        @XmlElement(name = "INITIAL_KEYWORD_2")
        protected String initialkeyword2;
        @XmlElement(name = "LINKER_FLAG_KEYWORD")
        protected String linkerflagkeyword;
        @XmlElement(name = "FINAL_KEYWORD_2")
        protected String finalkeyword2;
        @XmlElement(name = "DEFAULT_INITIAL_KEYWORD_1")
        protected String defaultinitialkeyword1;
        @XmlElement(name = "DEFAULT_INITIAL_KEYWORD_2")
        protected String defaultinitialkeyword2;

        public String getValue(final SECTION_KEYWORD sectionKeyword) {

          String value = "";
          switch (sectionKeyword) {

            case SHORT_NAME:
              return getSHORTNAME();
            case OPTIONAL_KEYWORD_1:
              return getOPTIONALKEYWORD1();
            case OPTIONAL_KEYWORD_2:
              return getOPTIONALKEYWORD2();
            case INITIAL_KEYWORD_1:
              return getINITIALKEYWORD1();
            case FINAL_KEYWORD_1:
              return getFINALKEYWORD1();
            case INITIAL_KEYWORD_2:
              return getINITIALKEYWORD2();
            case LINKER_FLAG_KEYWORD:
              return getLINKERFLAGKEYWORD();
            case FINAL_KEYWORD_2:
              return getFINALKEYWORD2();
            case DEFAULT_INITIAL_KEYWORD_1:
              return getDEFAULTINITIALKEYWORD1();
            case DEFAULT_INITIAL_KEYWORD_2:
              return getDEFAULTINITIALKEYWORD2();
            default:
              return value;
          }
        }

        /**
         * Gets the value of the shortname property.
         *
         * @return possible object is {@link String }
         */
        public String getSHORTNAME() {
          return this.shortname;
        }

        /**
         * Sets the value of the shortname property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setSHORTNAME(final String value) {
          this.shortname = value;
        }

        /**
         * Gets the value of the optionalkeyword1 property.
         * 
         * @return possible object is {@link String }
         */
        public String getOPTIONALKEYWORD1() {
          return this.optionalkeyword1;
        }

        /**
         * Sets the value of the optionalkeyword1 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setOPTIONALKEYWORD1(final String value) {
          this.optionalkeyword1 = value;
        }

        /**
         * Gets the value of the optionalkeyword2 property.
         * 
         * @return possible object is {@link String }
         */
        public String getOPTIONALKEYWORD2() {
          return this.optionalkeyword2;
        }

        /**
         * Sets the value of the optionalkeyword2 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setOPTIONALKEYWORD2(final String value) {
          this.optionalkeyword2 = value;
        }

        /**
         * Gets the value of the initialkeyword1 property.
         * 
         * @return possible object is {@link String }
         */
        public String getINITIALKEYWORD1() {
          return this.initialkeyword1;
        }

        /**
         * Sets the value of the initialkeyword1 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setINITIALKEYWORD1(final String value) {
          this.initialkeyword1 = value;
        }

        /**
         * Gets the value of the finalkeyword1 property.
         * 
         * @return possible object is {@link String }
         */
        public String getFINALKEYWORD1() {
          return this.finalkeyword1;
        }

        /**
         * Sets the value of the finalkeyword1 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setFINALKEYWORD1(final String value) {
          this.finalkeyword1 = value;
        }

        /**
         * Gets the value of the initialkeyword2 property.
         * 
         * @return possible object is {@link String }
         */
        public String getINITIALKEYWORD2() {
          return this.initialkeyword2;
        }

        /**
         * Sets the value of the initialkeyword2 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setINITIALKEYWORD2(final String value) {
          this.initialkeyword2 = value;
        }

        /**
         * Gets the value of the linkerflagkeyword property.
         * 
         * @return possible object is {@link String }
         */
        public String getLINKERFLAGKEYWORD() {
          return this.linkerflagkeyword;
        }

        /**
         * Sets the value of the linkerflagkeyword property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setLINKERFLAGKEYWORD(final String value) {
          this.linkerflagkeyword = value;
        }

        /**
         * Gets the value of the finalkeyword2 property.
         * 
         * @return possible object is {@link String }
         */
        public String getFINALKEYWORD2() {
          return this.finalkeyword2;
        }

        /**
         * Sets the value of the finalkeyword2 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setFINALKEYWORD2(final String value) {
          this.finalkeyword2 = value;
        }

        /**
         * Gets the value of the defaultinitialkeyword1 property.
         * 
         * @return possible object is {@link String }
         */
        public String getDEFAULTINITIALKEYWORD1() {
          return this.defaultinitialkeyword1;
        }

        /**
         * Sets the value of the defaultinitialkeyword1 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setDEFAULTINITIALKEYWORD1(final String value) {
          this.defaultinitialkeyword1 = value;
        }

        /**
         * Gets the value of the defaultinitialkeyword2 property.
         * 
         * @return possible object is {@link String }
         */
        public String getDEFAULTINITIALKEYWORD2() {
          return this.defaultinitialkeyword2;
        }

        /**
         * Sets the value of the defaultinitialkeyword2 property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setDEFAULTINITIALKEYWORD2(final String value) {
          this.defaultinitialkeyword2 = value;
        }

      }

    }

  }

}
